# Set the settings for the competition you want to play.
# Ignore other settings they will be ignored by game controller.

# Settings to be used for prisoners_dilemma game.
prisoners_dilemma:
  writer_parallelization: 0
  fixture_settings:
    format: roundrobin
    rounds: 5
    min_iterations: 400
    max_iterations: 500
  payoff_matrix: 
    win: 3
    mutual_cooperation: 2
    mutual_defection: 1
    loss: 0
  players:
    - appeaser
    - tit_for_tat
    - jesus
    - joker
    - judas
    - lucifer
    - grudger
    - better_and_better
    - worse_and_worse

# Settings to be used for sokoban solver game.
sokoban_solver:
  methods:
    - DFS
    - BFS
    - Astar
  output_dir: ./results
  levels_file: ./levels.json
