# Set the settings for the competition you want to play.
# Ignore other settings they will be ignored by game controller.

prisoners_dilemma:
  fixture_settings:
    format: roundrobin
    rounds: 5
    min_iterations: 300
    max_iterations: 700
  payoff_matrix: 
    win: 3
    mutual_cooperation: 2
    mutual_defection: 1
    loss: 0
  players:
    - tit_for_tat
    - jesus
    - joker
    - judas
    - lucifer
    - grudger
    - worse_and_worse